# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'persiantts' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  # Installed ones
  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

# do not allow Cocoapods to manage React dependencies
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
